### ISSUE TITLE
How to generate sampled_relative.csv, sampled.csv?

### ISSUE THREAD

**Issue by copark86** [HTLife/VINet#2]
Hi,
Thank you for sharing the code.

I am trying to run the code on my computer without docker and found these two files are missing. 
Could you kindly advice me how to create them?

**Comment by HTLife** [comment]
@copark86 
I just upload the script under [sciprt/](https://github.com/HTLife/VINet/tree/master/scripts) folder.

I still struggle with getting this implementation converge on training.  
If you got any idea of modifying the code, I'll be happy to discuss with you.

**Comment by copark86** [comment]
@HTLife Thanks! Sure, I will share the idea if there is a working one.

**Comment by angryBird2014** [comment]
Hi, I occur problem whe I run the script code with "convertSampledTrajToR6.py" , sophus.SO3 cannot construt object with 
`q = Quaternion(angle = q_real,vector = q_img) 

  R = sp.SO3(q)`, 
how to solve it ?

**Comment by HTLife** [comment]
@angryBird2014 Could you post the error message?

**Comment by angryBird2014** [comment]
Traceback (most recent call last):
  File "convertSampledTrajToR6.py", line 168, in <module>
    main()
  File "convertSampledTrajToR6.py", line 163, in main
    _get_filenames_and_classes('../mav0')
  File "convertSampledTrajToR6.py", line 130, in _get_filenames_and_classes
    relative_pose[7]])
  File "convertSampledTrajToR6.py", line 84, in xyzQuaternion2se3_
    R = sp.SO3(q)
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. sophus.sophuspy.SO3()
    2. sophus.sophuspy.SO3(other: sophus.sophuspy.SO3)
    3. sophus.sophuspy.SO3(other: numpy.ndarray[float64[3, 3]])

Invoked with: Quaternion(0.0, -0.0007431817228861249, 0.0004625481569996305, -0.0006017697731014128)

**Comment by angryBird2014** [comment]
> @angryBird2014 Could you post the error message?

I install sophus with "pip install sophuspy"

**Comment by HTLife** [comment]
@angryBird2014 Did you tried the docker image?
https://github.com/HTLife/VINet/wiki/Installation-Guide

**Comment by angryBird2014** [comment]
> @HTLife Thanks! Sure, I will share the idea if there is a working one.

Do you run the "script" code successfully?  I also run the code without docker, but found some problems with "convertSampledTrajToR6.py", can you tell me how to deal with the data with "script“ code?

**Comment by fangxu622** [comment]
@HTLife @angryBird2014  I have the same questions.

the " convertSampledTrajToR6.py" has some problem

**Comment by fangxu622** [comment]
Hi， why make the first number positive on quaternion?

```
def normalize(ww,wx,wy,wz):# make first number positive
    q = [ww, wx, wy, wz]
    ## Find first negative
    idx = -1
    for i in range(len(q)):
        if q[i] < 0:
            idx = i
            break
        elif q[i] > 0:
            break
    # -1 if should not filp, >=0  flipping index
    if idx >= 0:
        ww = ww * -1
        wx = wx * -1
        wy = wy * -1
        wz = wz * -1
    return ww, wx, wy, wz def normalize(ww,wx,wy,wz):# make first number positive
    q = [ww, wx, wy, wz]
    ## Find first negative
    idx = -1
    for i in range(len(q)):
        if q[i] < 0:
            idx = i
            break
        elif q[i] > 0:
            break
    # -1 if should not filp, >=0  flipping index
    if idx >= 0:
        ww = ww * -1
        wx = wx * -1
        wy = wy * -1
        wz = wz * -1
    return ww, wx, wy, wz 
```

**Comment by fangxu622** [comment]
Hi，I modified the function xyzQuaternion2se3_() like this to run correctly. please check @HTLife @copark86 @angryBird2014 

```
def xyzQuaternion2se3_(arr):
    x,y,z,ww,wx,wy,wz = arr[0], arr[1], arr[2], arr[3], arr[4], arr[5], arr[6]
    trans = np.array([x,y,z])
    ww, wx, wy, wz = normalize(ww, wx, wy, wz)
        
    #q_real = ww
    #q_img = Matrix([wx, wy, wz])
    q = Quaternion(ww, wx, wy, wz)
    R = q.to_rotation_matrix()
    
    RT = SE3(R, trans)
    #print(RT.log())
    numpy_vec = np.array(RT.log()).astype(float)  # SE3 to se3
    
    return numpy_vec
```

the origin 
```
def xyzQuaternion2se3_(arr):
    x,y,z,ww,wx,wy,wz = arr[0], arr[1], arr[2], arr[3], arr[4], arr[5], arr[6]
    trans = Matrix([x,y,z])
    ww, wx, wy, wz = normalize(ww, wx, wy, wz)
        
    q_real = ww
    q_img = Matrix([wx, wy, wz])
    q = Quaternion(q_real,q_img)
    R = So3(q)
    
    RT = Se3(R, trans)
    #print(RT.log())
    numpy_vec = np.array(RT.log()).astype(float)  # SE3 to se3
    
    return np.concatenate(numpy_vec)
```
