### ISSUE TITLE
Problem during installation via docker

### ISSUE THREAD

**Issue by DaddyWesker** [HTLife/VINet#4]
Hi!

During installation process i've met a problem.
Trying this
sudo nvidia-docker run --shm-size 8G --restart=always -d --name vinet -e PASSWORD='vinet' -p 192.168.0.1:8888:8888 -p 192.168.0.1:6006:6006 -p 192.168.0.1:52022:22 -v /home/daddywesker/dockerData:/notebooks/data:z jjkka132/vinet:latest /bin/sh -c "while true; do sleep 10; done"

getting:
8e8fa3686a5ce9f7efec819ed1511a86f0ba238a0a2f78575b6cb76a03ce331e
docker: Error response from daemon: driver failed programming external connectivity on endpoint vinet (541de2c471e5b0b45b7a92eb985483560bc95cc69ddd39536aefeee05493301f): Error starting userland proxy: listen tcp 192.168.0.1:8888: bind: cannot assign requested address.

Well, i've tried to avoid this by just cloning repository, installing all dependencies for project and launch "main.py". But i need saved model AND euroc_modify (tried to load euroc dataset but it doesnt have some files which your code requesting)

Can you help me with any of this?

**Comment by HTLife** [comment]
The 8888 port setting might conflict with existed container.  You could skip the port setting and mount folder to get the data inside.
